[project]
name = "attention-is-all-that-u-need"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dataclasses>=0.8",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "typing>=3.10.0.0",
]
